# Site settings
title:       Goyllo
email:       contact@goyllo.com
author:      Arjunsinh Chauhan
baseurl:     ""
url:         "https://www.goyllo.com"


# Optional features
animated:           true
show_post_footers:  true
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 

# Social icons
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
gems:
  - jekyll-redirect-from
  
include: ['_pages']
markdown:     kramdown
permalink:    pretty
paginate:     20
sass:
  compressed: true
