# Site settings
title: Goyllo
email: arjun@goyllo.com
description: > # this means to ignore newlines until "baseurl:"
 Get useful guidelines on internet and software tutorials.
baseurl: "" # the subpath of your site, e.g. /blog/
imgurl: https://img.goyllo.com
url: "https://www.goyllo.com" # the base hostname & protocol for your site
twitter_username: Goyllocom
github_username:  goyllo

# Build settings
markdown: kramdown
permalink: none

include: ['_pages']


gems:
  - jekyll-redirect-from
